apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillorbit-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: backend

          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.imagePullPolicy }}

          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
              httpGet:
                path: /actuator/health/readiness
                port: 8080

              initialDelaySeconds: 20
              periodSeconds: 10

              timeoutSeconds: 5

              failureThreshold: 3
          livenessProbe:
              httpGet:
                path: /actuator/health/liveness
                port: 8080

              initialDelaySeconds: 60
              periodSeconds: 15

              timeoutSeconds: 5

              failureThreshold: 3
