apiVersion: v1
kind: Service
metadata:
  name: postgres

spec:
  type: {{ .Values.postgres.service.type }}

  selector:
    app: postgres

  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: 5432